import { Listing } from '../../src/types';

export const MOCK_FILTERED_LISTING_1 = [
  {
    address: '8848 Saint Clair St',
    agentEmail: 'No data found',
    agentLicenseNumber: '0995705128',
    agentName: 'Steven Mabry',
    agentPhoneNumber: '318-868-3600',
    askingPrice: '$179,900',
    baths: '3',
    beds: '4',
    daysOnMarket: '84',
    listingLink:
      'https://www.zillow.com/homedetails/8848-Saint-Clair-St-Shreveport-LA-71118/51373320_zpid/',
    mls: '20651336',
    offerPrice: '$125,930',
    sqft: '2172',
    zip: '71118',
    zpid: '51373320',
  },
  {
    address: '5544 Lexington Ave',
    agentEmail: 'agent.james@example.com',
    agentLicenseNumber: '0987654321',
    agentName: 'James Morgan',
    agentPhoneNumber: '318-555-1234',
    askingPrice: '$249,500',
    baths: '2.5',
    beds: '3',
    daysOnMarket: '45',
    listingLink:
      'https://www.zillow.com/homedetails/5544-Lexington-Ave-Shreveport-LA-71106/51212345_zpid/',
    mls: '20765432',
    offerPrice: '$230,000',
    sqft: '1800',
    zip: '71106',
    zpid: '51212345',
  },
  {
    address: '3621 Willow Oak Dr',
    agentEmail: 'contact.steve@example.com',
    agentLicenseNumber: '0776543210',
    agentName: 'Steve Hunter',
    agentPhoneNumber: '318-444-9876',
    askingPrice: '$199,000',
    baths: '3',
    beds: '4',
    daysOnMarket: '102',
    listingLink:
      'https://www.zillow.com/homedetails/3621-Willow-Oak-Dr-Shreveport-LA-71119/51409876_zpid/',
    mls: '20871234',
    offerPrice: '$180,500',
    sqft: '2345',
    zip: '71119',
    zpid: '51409876',
  },
  {
    address: '4821 Maplewood Cir',
    agentEmail: 'maplewood.agent@example.com',
    agentLicenseNumber: '0664321876',
    agentName: 'Lucy Thompson',
    agentPhoneNumber: '318-222-7654',
    askingPrice: '$310,000',
    baths: '4',
    beds: '5',
    daysOnMarket: '21',
    listingLink:
      'https://www.zillow.com/homedetails/4821-Maplewood-Cir-Shreveport-LA-71107/51543218_zpid/',
    mls: '20981234',
    offerPrice: '$290,000',
    sqft: '3200',
    zip: '71107',
    zpid: '51543218',
  },
];

export const MOCK_FILTERED_LISTING_2 = [
  {
    address: '8848 Saint Clair St',
    agentEmail: 'No data found',
    agentLicenseNumber: '0995705128',
    agentName: 'Steven Mabry',
    agentPhoneNumber: '318-868-3600',
    askingPrice: '$179,900',
    baths: '3',
    beds: '4',
    daysOnMarket: '84',
    listingLink:
      'https://www.zillow.com/homedetails/8848-Saint-Clair-St-Shreveport-LA-71118/51373320_zpid/',
    mls: '20651336',
    offerPrice: '$125,930',
    sqft: '2172',
    zip: '71118',
    zpid: '51373320',
  },
  {
    address: '5544 Lexington Ave',
    agentEmail: 'agent.james@example.com',
    agentLicenseNumber: '0987654321',
    agentName: 'James Morgan',
    agentPhoneNumber: '318-555-1234',
    askingPrice: '$249,500',
    baths: '2.5',
    beds: '3',
    daysOnMarket: '45',
    listingLink:
      'https://www.zillow.com/homedetails/5544-Lexington-Ave-Shreveport-LA-71106/51212345_zpid/',
    mls: '20765432',
    offerPrice: '$230,000',
    sqft: '1800',
    zip: '71106',
    zpid: '51212345',
  },
  {
    address: '1207 Pine Hill Rd',
    agentEmail: 'pine.agent@example.com',
    agentLicenseNumber: '0779812345',
    agentName: 'Olivia White',
    agentPhoneNumber: '318-999-5432',
    askingPrice: '$210,000',
    baths: '2',
    beds: '3',
    daysOnMarket: '56',
    listingLink:
      'https://www.zillow.com/homedetails/1207-Pine-Hill-Rd-Shreveport-LA-71108/51298765_zpid/',
    mls: '21098765',
    offerPrice: '$200,000',
    sqft: '1950',
    zip: '71108',
    zpid: '51298765',
  },
  {
    address: '3901 Lakeside Dr',
    agentEmail: 'lakeside.agent@example.com',
    agentLicenseNumber: '0551234678',
    agentName: 'Emily Turner',
    agentPhoneNumber: '318-876-5432',
    askingPrice: '$315,000',
    baths: '3.5',
    beds: '4',
    daysOnMarket: '30',
    listingLink:
      'https://www.zillow.com/homedetails/3901-Lakeside-Dr-Shreveport-LA-71109/51678910_zpid/',
    mls: '21123456',
    offerPrice: '$305,000',
    sqft: '2800',
    zip: '71109',
    zpid: '51678910',
  },
];

export const MOCK_FILTERED_LISTING_3 = [
  {
    address: '4209 Elmwood Dr',
    agentEmail: 'elmwood.agent@example.com',
    agentLicenseNumber: '0987123456',
    agentName: 'Liam Johnson',
    agentPhoneNumber: '318-555-7890',
    askingPrice: '$320,000',
    baths: '3',
    beds: '4',
    daysOnMarket: '20',
    listingLink:
      'https://www.zillow.com/homedetails/4209-Elmwood-Dr-Shreveport-LA-71108/51765432_zpid/',
    mls: '21234567',
    offerPrice: '$310,000',
    sqft: '2450',
    zip: '71108',
    zpid: '51765432',
  },
  {
    address: '2310 Cedar Ridge Ct',
    agentEmail: 'cedar.agent@example.com',
    agentLicenseNumber: '0654321876',
    agentName: 'Sophia Garcia',
    agentPhoneNumber: '318-876-4321',
    askingPrice: '$289,500',
    baths: '2.5',
    beds: '3',
    daysOnMarket: '12',
    listingLink:
      'https://www.zillow.com/homedetails/2310-Cedar-Ridge-Ct-Shreveport-LA-71119/51843210_zpid/',
    mls: '21387654',
    offerPrice: '$280,000',
    sqft: '2200',
    zip: '71119',
    zpid: '51843210',
  },
  {
    address: '1501 Maple Leaf Dr',
    agentEmail: 'mapleleaf.agent@example.com',
    agentLicenseNumber: '0776543219',
    agentName: 'Noah Martinez',
    agentPhoneNumber: '318-654-3210',
    askingPrice: '$355,000',
    baths: '4',
    beds: '5',
    daysOnMarket: '8',
    listingLink:
      'https://www.zillow.com/homedetails/1501-Maple-Leaf-Dr-Shreveport-LA-71107/51987612_zpid/',
    mls: '21465432',
    offerPrice: '$345,000',
    sqft: '3000',
    zip: '71107',
    zpid: '51987612',
  },
  {
    address: '8932 Ridgeview Ln',
    agentEmail: 'ridgeview.agent@example.com',
    agentLicenseNumber: '0998765432',
    agentName: 'Ava Brown',
    agentPhoneNumber: '318-543-2109',
    askingPrice: '$415,000',
    baths: '3.5',
    beds: '4',
    daysOnMarket: '35',
    listingLink:
      'https://www.zillow.com/homedetails/8932-Ridgeview-Ln-Shreveport-LA-71106/52012345_zpid/',
    mls: '21543210',
    offerPrice: '$400,000',
    sqft: '3250',
    zip: '71106',
    zpid: '52012345',
  },
];

export const MOCK_LISTING_1: Listing[] = [
  {
    zpid: '12345678',
    id: 'L-123',
    providerListingId: null,
    imgSrc: 'https://example.com/img1.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property1',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$350,000',
    unformattedPrice: 350000,
    address: '123 Maple St',
    addressStreet: '123 Maple St',
    addressCity: 'Springfield',
    addressState: 'IL',
    addressZipcode: '62704',
    isUndisclosedAddress: false,
    beds: 3,
    baths: 2,
    area: 1800,
    latLong: { lat: 39.7817, lon: -89.6501 },
    isZillowOwned: false,
    variableData: { type: 'PRICE_REDUCTION', text: 'Price reduced by $5,000' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 12345678,
        streetAddress: '123 Maple St',
        zipcode: '62704',
        city: 'Springfield',
        state: 'IL',
        latitude: 39.7817,
        longitude: -89.6501,
        price: 350000,
        bathrooms: 2,
        bedrooms: 3,
        livingArea: 1800,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 10,
        isFeatured: false,
        shouldHighlight: false,
        zestimate: 340000,
        rentZestimate: 2000,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 350000,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 320000,
        lotAreaValue: 0.5,
        lotAreaUnit: 'acres',
        isShowcaseListing: false,
      },
    },
    isSaved: false,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 340000,
    shouldShowZestimateAsPrice: false,
    has3DModel: false,
    hasVideo: true,
    isHomeRec: true,
    info2String: '3 beds, 2 baths, 1,800 sqft',
    brokerName: 'John Realty',
    hasAdditionalAttributions: false,
    isFeaturedListing: false,
    isShowcaseListing: false,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
  {
    zpid: '87654321',
    id: 'L-876',
    providerListingId: null,
    imgSrc: 'https://example.com/img2.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property2',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$475,000',
    unformattedPrice: 475000,
    address: '456 Oak St',
    addressStreet: '456 Oak St',
    addressCity: 'Chicago',
    addressState: 'IL',
    addressZipcode: '60614',
    isUndisclosedAddress: false,
    beds: 4,
    baths: 3,
    area: 2200,
    latLong: { lat: 41.8781, lon: -87.6298 },
    isZillowOwned: false,
    variableData: { type: 'NEW_LISTING', text: 'Just Listed' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 87654321,
        streetAddress: '456 Oak St',
        zipcode: '60614',
        city: 'Chicago',
        state: 'IL',
        latitude: 41.8781,
        longitude: -87.6298,
        price: 475000,
        bathrooms: 3,
        bedrooms: 4,
        livingArea: 2200,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 5,
        isFeatured: true,
        shouldHighlight: true,
        zestimate: 460000,
        rentZestimate: 2500,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 475000,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 450000,
        lotAreaValue: 0.2,
        lotAreaUnit: 'acres',
        isShowcaseListing: true,
      },
    },
    isSaved: true,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 460000,
    shouldShowZestimateAsPrice: false,
    has3DModel: true,
    hasVideo: false,
    isHomeRec: true,
    info2String: '4 beds, 3 baths, 2,200 sqft',
    brokerName: 'Jane Realty',
    hasAdditionalAttributions: true,
    isFeaturedListing: true,
    isShowcaseListing: true,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
  {
    zpid: '11223344',
    id: 'L-112',
    providerListingId: null,
    imgSrc: 'https://example.com/img3.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property3',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$299,900',
    unformattedPrice: 299900,
    address: '789 Pine St',
    addressStreet: '789 Pine St',
    addressCity: 'Peoria',
    addressState: 'IL',
    addressZipcode: '61615',
    isUndisclosedAddress: false,
    beds: 3,
    baths: 2.5,
    area: 1900,
    latLong: { lat: 40.6936, lon: -89.5889 },
    isZillowOwned: false,
    variableData: { type: 'NEW_LISTING', text: 'Just Listed' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 11223344,
        streetAddress: '789 Pine St',
        zipcode: '61615',
        city: 'Peoria',
        state: 'IL',
        latitude: 40.6936,
        longitude: -89.5889,
        price: 299900,
        bathrooms: 2.5,
        bedrooms: 3,
        livingArea: 1900,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 15,
        isFeatured: false,
        shouldHighlight: false,
        zestimate: 290000,
        rentZestimate: 1800,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 299900,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 270000,
        lotAreaValue: 0.3,
        lotAreaUnit: 'acres',
        isShowcaseListing: false,
      },
    },
    isSaved: true,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 290000,
    shouldShowZestimateAsPrice: false,
    has3DModel: false,
    hasVideo: false,
    isHomeRec: false,
    info2String: '3 beds, 2.5 baths, 1,900 sqft',
    brokerName: 'Sara Realty',
    hasAdditionalAttributions: false,
    isFeaturedListing: false,
    isShowcaseListing: false,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
];

export const MOCK_LISTING_2: Listing[] = [
  {
    zpid: '12345678', // Same as in Array 1
    id: 'L-123',
    providerListingId: null,
    imgSrc: 'https://example.com/img1.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property1',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$350,000',
    unformattedPrice: 350000,
    address: '123 Maple St',
    addressStreet: '123 Maple St',
    addressCity: 'Springfield',
    addressState: 'IL',
    addressZipcode: '62704',
    isUndisclosedAddress: false,
    beds: 3,
    baths: 2,
    area: 1800,
    latLong: { lat: 39.7817, lon: -89.6501 },
    isZillowOwned: false,
    variableData: { type: 'PRICE_REDUCTION', text: 'Price reduced by $5,000' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 12345678,
        streetAddress: '123 Maple St',
        zipcode: '62704',
        city: 'Springfield',
        state: 'IL',
        latitude: 39.7817,
        longitude: -89.6501,
        price: 350000,
        bathrooms: 2,
        bedrooms: 3,
        livingArea: 1800,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 10,
        isFeatured: false,
        shouldHighlight: false,
        zestimate: 340000,
        rentZestimate: 2000,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 350000,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 320000,
        lotAreaValue: 0.5,
        lotAreaUnit: 'acres',
        isShowcaseListing: false,
      },
    },
    isSaved: false,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 340000,
    shouldShowZestimateAsPrice: false,
    has3DModel: false,
    hasVideo: true,
    isHomeRec: true,
    info2String: '3 beds, 2 baths, 1,800 sqft',
    brokerName: 'John Realty',
    hasAdditionalAttributions: false,
    isFeaturedListing: false,
    isShowcaseListing: false,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
  {
    zpid: '44556677',
    id: 'L-445',
    providerListingId: null,
    imgSrc: 'https://example.com/img4.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property4',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$520,000',
    unformattedPrice: 520000,
    address: '987 Willow Dr',
    addressStreet: '987 Willow Dr',
    addressCity: 'Naperville',
    addressState: 'IL',
    addressZipcode: '60540',
    isUndisclosedAddress: false,
    beds: 5,
    baths: 3.5,
    area: 3000,
    latLong: { lat: 41.7508, lon: -88.1535 },
    isZillowOwned: false,
    variableData: { type: 'NEW_LISTING', text: 'Just Listed' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 44556677,
        streetAddress: '987 Willow Dr',
        zipcode: '60540',
        city: 'Naperville',
        state: 'IL',
        latitude: 41.7606,
        longitude: -88.3201,
        price: 520000,
        bathrooms: 3.5,
        bedrooms: 5,
        livingArea: 3000,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 7,
        isFeatured: false,
        shouldHighlight: false,
        zestimate: 280000,
        rentZestimate: 1750,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 290000,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 270000,
        lotAreaValue: 0.25,
        lotAreaUnit: 'acres',
        isShowcaseListing: false,
      },
    },
    isSaved: false,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 505000,
    shouldShowZestimateAsPrice: false,
    has3DModel: false,
    hasVideo: false,
    isHomeRec: true,
    info2String: '5 beds, 3.5 baths, 3,000 sqft',
    brokerName: 'Paul Realty',
    hasAdditionalAttributions: true,
    isFeaturedListing: false,
    isShowcaseListing: false,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
  {
    zpid: '99887766',
    id: 'L-998',
    providerListingId: null,
    imgSrc: 'https://example.com/img5.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property5',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$290,000',
    unformattedPrice: 290000,
    address: '321 Cedar Ave',
    addressStreet: '321 Cedar Ave',
    addressCity: 'Aurora',
    addressState: 'IL',
    addressZipcode: '60506',
    isUndisclosedAddress: false,
    beds: 3,
    baths: 2,
    area: 1700,
    latLong: { lat: 41.7606, lon: -88.3201 },
    isZillowOwned: false,
    variableData: { type: 'NEW_LISTING', text: 'Just Listed' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 99887766,
        streetAddress: '321 Cedar Ave',
        zipcode: '60506',
        city: 'Aurora',
        state: 'IL',
        latitude: 41.7606,
        longitude: -88.3201,
        price: 290000,
        bathrooms: 2,
        bedrooms: 3,
        livingArea: 1700,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 7,
        isFeatured: false,
        shouldHighlight: false,
        zestimate: 280000,
        rentZestimate: 1750,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 290000,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 270000,
        lotAreaValue: 0.25,
        lotAreaUnit: 'acres',
        isShowcaseListing: false,
      },
    },
    isSaved: true,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 280000,
    shouldShowZestimateAsPrice: false,
    has3DModel: false,
    hasVideo: true,
    isHomeRec: true,
    info2String: '3 beds, 2 baths, 1,700 sqft',
    brokerName: 'Lucy Realty',
    hasAdditionalAttributions: false,
    isFeaturedListing: true,
    isShowcaseListing: true,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
  {
    zpid: '11223344',
    id: 'L-112',
    providerListingId: null,
    imgSrc: 'https://example.com/img3.jpg',
    hasImage: true,
    carouselPhotos: [],
    detailUrl: 'https://example.com/property3',
    statusType: 'FOR_SALE',
    statusText: 'For Sale',
    countryCurrency: 'USD',
    price: '$299,900',
    unformattedPrice: 299900,
    address: '789 Pine St',
    addressStreet: '789 Pine St',
    addressCity: 'Peoria',
    addressState: 'IL',
    addressZipcode: '61615',
    isUndisclosedAddress: false,
    beds: 3,
    baths: 2.5,
    area: 1900,
    latLong: { lat: 40.6936, lon: -89.5889 },
    isZillowOwned: false,
    variableData: { type: 'NEW_LISTING', text: 'Just Listed' },
    badgeInfo: null,
    hdpData: {
      homeInfo: {
        zpid: 11223344,
        streetAddress: '789 Pine St',
        zipcode: '61615',
        city: 'Peoria',
        state: 'IL',
        latitude: 40.6936,
        longitude: -89.5889,
        price: 299900,
        bathrooms: 2.5,
        bedrooms: 3,
        livingArea: 1900,
        homeType: 'SingleFamily',
        homeStatus: 'FOR_SALE',
        daysOnZillow: 15,
        isFeatured: false,
        shouldHighlight: false,
        zestimate: 290000,
        rentZestimate: 1800,
        listing_sub_type: {
          is_newHome: false,
          is_FSBO: false,
          is_FSBA: false,
          is_foreclosure: false,
          is_bankOwned: false,
          is_forAuction: false,
          is_comingSoon: false,
          is_pending: false,
          is_openHouse: false,
        },
        isUnmappable: false,
        isPreforeclosureAuction: false,
        homeStatusForHDP: 'FOR_SALE',
        priceForHDP: 299900,
        isNonOwnerOccupied: false,
        isPremierBuilder: false,
        isZillowOwned: false,
        currency: 'USD',
        country: 'USA',
        taxAssessedValue: 270000,
        lotAreaValue: 0.3,
        lotAreaUnit: 'acres',
        isShowcaseListing: false,
      },
    },
    isSaved: true,
    isUserClaimingOwner: false,
    isUserConfirmedClaim: false,
    pgapt: 'ForSale',
    sgapt: 'ForSale',
    zestimate: 290000,
    shouldShowZestimateAsPrice: false,
    has3DModel: false,
    hasVideo: false,
    isHomeRec: false,
    info2String: '3 beds, 2.5 baths, 1,900 sqft',
    brokerName: 'Sara Realty',
    hasAdditionalAttributions: false,
    isFeaturedListing: false,
    isShowcaseListing: false,
    availabilityDate: null,
    list: true,
    relaxed: false,
  },
];
